project: ""
destination:
  name: argus
  server: ""
  namespace: dev-portal

postgresql:
  enabled: true
  targetRevision: 15.5.32

backend:
  enabled: true
  targetRevision: deploy-with-argocd-tmp

frontend:
  enabled: true
  targetRevision: deploy-with-argocd-tmp
