apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-portal-backend
  description: The diamond developer portal backend.
spec:
  type: website
  lifecycle: experimental
  system: developer-portal
  owner: user:enu43627
  dependsOn:
    - component:developer-guide
  providesApis:
    - developer-portal-backend-rest
