apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-portal-frontend
  title: Developer Portal Frontend
  description: A single page application which displays the developer portal as provided by the backend.
spec:
  type: website
  lifecycle: experimental
  system: developer-portal
  owner: user:enu43627
  consumesApis:
    - developer-portal-backend-rest
