apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: developer-portal
  description: The diamond developer portal.
spec:
  type: file
  targets:
    - ./catalog-info/system.yaml
    - ./catalog-info/frontend.yaml
    - ./catalog-info/backend.yaml
    - ./catalog-info/backend-api.yaml
