apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: developer-portal
  title: Developer Portal
  description: The diamond developer portal.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  owner: user:enu43627

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-portal-backend
  title: Developer Portal Backend
  description: A node application performing discovery and providing the developer portal REST API.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: DiamondLightSource/developer-portal
spec:
  type: service
  lifecycle: production
  system: developer-portal
  owner: user:enu43627
  dependsOn:
    - component:developer-guide
    - resource:developer-portal-techdocs-bucket
  providesApis:
    - developer-portal-backend-rest

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: developer-portal-backend-rest
  title: Developer Portal Backend REST API
  description: A RESTful API exposed by the developer portal backend.
spec:
  type: openapi
  lifecycle: production
  owner: user:enu43627
  system: developer-portal
  definition: |
    openapi: 3.0.0
    info:
      title: Backstage API
      version: 0.0.1

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-portal-frontend
  title: Developer Portal Frontend
  description: A single page application which displays the developer portal as provided by the backend.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: DiamondLightSource/developer-portal
spec:
  type: website
  lifecycle: production
  system: developer-portal
  owner: user:enu43627
  consumesApis:
    - developer-portal-backend-rest

---

apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: developer-portal-techdocs-bucket
  title: Developer Portal Techdocs Bucket
  description: An AWS S3 compatible object store containing built techdocs documentation
spec:
  type: s3-bucket
  system: developer-portal
  owner: enu43627
