apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: developer-portal
  title: Developer Portal
  description: The diamond developer portal.
  annotations:
    diamond.ac.uk/linkdocs-url: https://diamondlightsource.github.io/developer-portal/
spec:
  owner: user:enu43627

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-portal-backend
  title: Developer Portal Backend
  description: A node application performing discovery and providing the developer portal REST API.
  annotations:
    github.com/project-slug: DiamondLightSource/developer-portal
    diamond.ac.uk/linkdocs-url: https://diamondlightsource.github.io/developer-portal/
spec:
  type: service
  lifecycle: experimental
  system: developer-portal
  owner: user:enu43627
  dependsOn:
    - component:developer-guide
  providesApis:
    - developer-portal-backend-rest

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: developer-portal-backend-rest
  title: Developer Portal Backend REST API
  description: A RESTful API exposed by the developer portal backend.
  annotations:
    diamond.ac.uk/linkdocs-url: https://diamondlightsource.github.io/developer-portal/
spec:
  type: openapi
  lifecycle: experimental
  owner: user:enu43627
  system: developer-portal
  definition: |
    openapi: 3.0.0
    info:
      title: Backstage API
      version: 0.0.1

---

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: developer-portal-frontend
  title: Developer Portal Frontend
  description: A single page application which displays the developer portal as provided by the backend.
  annotations:
    github.com/project-slug: DiamondLightSource/developer-portal
    diamond.ac.uk/linkdocs-url: https://diamondlightsource.github.io/developer-portal/
spec:
  type: website
  lifecycle: experimental
  system: developer-portal
  owner: user:enu43627
  consumesApis:
    - developer-portal-backend-rest
