site_name: Developer Portal
site_url: https://0.0.0.0/
repo_url: https://github.com/DiamondLightSource/developer-portal
edit_uri: edit/main/docs/
plugins:
  - techdocs-core
  - include-markdown
  - include_dir_to_nav:
      file_pattern: '.*(?<!index)\.md$'
  - awesome-pages
  - pagenav-generator
nav:
  - Home: index.md
  - Tutorials: 
    - Home: tutorials/index.md
    - tutorials
  - 'How Tos':
    - Home: how-tos/index.md
    - how-tos
  - Explanations:
    - Home: explanations/index.md
    - explanations
  - References:
    - Home: references/index.md
    - references
