apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.common.componentLabel }}-backend
    app.kubernetes.io/part-of: {{ .Values.common.componentLabel }}
    {{- if .Values.commonLabels -}}
    {{ include "common.tplvalues.render" ( dict "value" .Values.common.labels "context" $ ) | nindent 4 }}
    {{ end }}
  annotations:
    {{- if .Values.common.annotations -}}
    {{ include "common.tplvalues.render" ( dict "value" .Values.common.annotations "context" $ ) | nindent 4 }}
    {{ end }}
spec:
  type: ClusterIP
  {{- if .Values.backendService.clusterIP -}}
  clusterIP: {{ .Values.backendService.clusterIP }}
  {{ end }}
  ports:
    - name: http-backend
      port: {{ .Values.backendService.port }}
      targetPort: {{ .Values.backendService.targetPort }}
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.common.componentLabel }}-backend
