apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "common.labels.matchLabels" $ | nindent 4 }}
  ports:
    - name: http-serve
      port: 80
      targetPort: http-serve
      protocol: TCP
