apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-backend
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.common.componentLabel }}-backend
    app.kubernetes.io/part-of: {{ .Values.common.componentLabel }}
    {{- if .Values.commonLabels -}}
    {{ include "common.tplvalues.render" ( dict "value" .Values.common.labels "context" $ ) | nindent 4 }}
    {{ end }}
  annotations:
    {{- if .Values.common.annotations -}}
    {{ include "common.tplvalues.render" ( dict "value" .Values.common.annotations "context" $ ) | nindent 4 }}
    {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.names.fullname" . }}-backend
      app.kubernetes.io/component: {{ .Values.common.componentLabel }}-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.names.fullname" . }}-backend
        app.kubernetes.io/component: {{ .Values.common.componentLabel }}-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "devportal.serviceAccountName" . }}
      {{- if .Values.backend.podSecurityContext -}}
      securityContext:
        {{ include "common.tplvalues.render " ( dict "value" .Values.backend.podSecurityContext "context" $ ) | nindent 8 }}
      {{ end }}
      {{- if .Values.backend.tolerations -}}
      tolerations:
        {{ include "common.tplvalues.render" ( dict "value" .Values.backend.tolerations "context" $ ) | nindent 8 }}
      {{ end }}
      {{- if .Values.backend.image.pullSecrets -}}
      imagePullSecrets:
      {{- range .Values.backend.image.pullSecrets -}}
        - name: {{- . -}}
      {{ end }}
      {{ end }}
      containers:
        - name: backstage-backend
          image: {{ include "devportal.backend.image" . }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | quote }}
          {{ if .Values.backend.containerSecurityContext }}
          securityContext: {{ include "common.tplvalues.render" ( dict "value" .Values.backend.containerSecurityContext "context" $ ) | nindent 12 }}
          {{ end }}
          {{- if .Values.backend.command -}}
          command: {{ include "common.tplvalues.render" ( dict "value" .Values.backend.command "context" $ ) | nindent 12 }}
          {{ end }}
          args:
          {{- range .Values.backend.args -}}
            - {{- . | quote -}}
          {{ end }}
          resources: {{ include "common.tplvalues.render" ( dict "value" .Values.backend.resources "context" $ ) | nindent 12 }}
          env:
            - name: POSTGRES_HOST
              value: {{ include "devportal.postgres.host" . }}
            - name: POSTGRES_PORT
              value: {{ include "devportal.postgres.port" . }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "devportal.postgres.secret.name" . }}
                  key: {{ include "devportal.postgres.secret.passwordKey" . }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "devportal.backend.auth.secret" . }}
                  key: {{ .Values.backend.auth.secretKeys.githubTokenKey }}
            - name: GITHUB_APP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "devportal.backend.auth.secret" . }}
                  key: {{ .Values.backend.auth.secretKeys.githubAppClientIdKey }}
            - name: GITHUB_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "devportal.backend.auth.secret" . }}
                  key: {{ .Values.backend.auth.secretKeys.githubAppSecretKey }}
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "devportal.backend.auth.secret" . }}
                  key: {{ .Values.backend.auth.secretKeys.gitlabTokenKey }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "devportal.backend.auth.secret" . }}
                  key: {{ .Values.backend.auth.secretKeys.s3AccessKeyIdKey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "devportal.backend.auth.secret" . }}
                  key: {{ .Values.backend.auth.secretKeys.s3AccessKeySecretKey }}
            - name: APP_CONFIG_app_baseUrl
              value: {{ print "https://" }}{{ .Values.ingress.host }}
            - name: APP_CONFIG_backend_baseUrl
              value: {{ print "https://" }}{{ .Values.ingress.host }}
          ports:
            - name: http-api
              containerPort: {{ .Values.backend.port }}
