version: "3.8"

x-postgres-variables: &postgres-variables
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres

services:
  backstage:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached,Z
    network_mode: service:database
    command: sleep infinity
    environment:
      <<: *postgres-variables
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PORT: 5432
    env_file:
      - .env

  database:
    image: postgres:15-bullseye
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      <<: *postgres-variables
      POSTGRES_DB: postgres

volumes:
  postgres-data:
