name: Helm CI

on:
  push:
  pull_request:

jobs:
  lint:
    # pull requests are a duplicate of a branch push if within the same repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Setup Python
        uses: actions/setup-python@v5.4.0

      - name: Setup chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Install chart dependencies
        run: helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Lint
        run: >
          ct lint
          --target-branch=${{ github.event.repository.default_branch }}
          --validate-maintainers=false
